"use client"
import { useRef,useState } from "react"
import type { SongRequestSettings } from "@/lib/song-requests/types"
const money=(c:number,currency:string)=>new Intl.NumberFormat("es-ES",{style:"currency",currency,minimumFractionDigits:c%100?2:0}).format(c/100)
export function RequestForm({settings,limitReached}:{settings:SongRequestSettings;limitReached:boolean}){
 const [error,setError]=useState("");const [loading,setLoading]=useState(false);const requestId=useRef(crypto.randomUUID());const disabled=settings.serviceStatus!=="open"||limitReached
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(loading)return;setLoading(true);setError("");const f=new FormData(event.currentTarget);try{const response=await fetch("/api/song-requests",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({songTitle:f.get("songTitle"),artistName:f.get("artistName"),requesterName:f.get("requesterName"),locationLabel:f.get("locationLabel"),dedication:f.get("dedication"),website:f.get("website"),clientRequestId:requestId.current})});const data=await response.json();if(!response.ok)throw new Error(data.error);window.location.assign(data.checkoutUrl)}catch(e){setError(e instanceof Error?e.message:"No se pudo enviar");setLoading(false)}}
 return <form onSubmit={submit} className="space-y-4" aria-describedby="request-notice">
  <label className="block font-semibold">Canción <span aria-hidden="true">*</span><input name="songTitle" required maxLength={160} autoComplete="off" enterKeyHint="next" className="mt-2 min-h-14 w-full rounded-xl border-2 border-white/20 bg-white/10 px-4 text-lg focus:border-primary focus:outline-none focus:ring-4 focus:ring-primary/30"/></label>
  <label className="block font-semibold">Artista <span className="text-sm font-normal text-white/60">(recomendado)</span><input name="artistName" maxLength={160} autoComplete="off" enterKeyHint="next" className="mt-2 min-h-14 w-full rounded-xl border-2 border-white/20 bg-white/10 px-4 text-lg focus:border-primary focus:outline-none focus:ring-4 focus:ring-primary/30"/></label>
  <div className="grid grid-cols-2 gap-3"><label className="block font-semibold">Tu nombre <span className="sr-only">opcional</span><input name="requesterName" maxLength={80} autoComplete="nickname" className="mt-2 min-h-14 w-full rounded-xl border-2 border-white/20 bg-white/10 px-3 focus:border-primary focus:outline-none focus:ring-4 focus:ring-primary/30"/></label><label className="block font-semibold">Mesa o zona <span className="sr-only">opcional</span><input name="locationLabel" maxLength={80} autoComplete="off" className="mt-2 min-h-14 w-full rounded-xl border-2 border-white/20 bg-white/10 px-3 focus:border-primary focus:outline-none focus:ring-4 focus:ring-primary/30"/></label></div>
  {settings.dedicationsEnabled&&<label className="block font-semibold">Dedicatoria <span className="text-sm font-normal text-white/60">(opcional)</span><textarea name="dedication" maxLength={240} rows={2} className="mt-2 w-full rounded-xl border-2 border-white/20 bg-white/10 px-4 py-3 focus:border-primary focus:outline-none focus:ring-4 focus:ring-primary/30"/></label>}
  <label className="absolute left-[-9999px]" aria-hidden="true">No rellenar<input name="website" tabIndex={-1} autoComplete="off"/></label>
  {error&&<p role="alert" className="rounded-lg border border-red-400 bg-red-950 p-3 text-red-100">{error}</p>}
  <button disabled={disabled||loading} className="min-h-16 w-full rounded-2xl bg-primary px-5 text-lg font-black text-primary-foreground shadow-lg focus:outline-none focus:ring-4 focus:ring-white disabled:cursor-not-allowed disabled:opacity-50">{loading?"Preparando…":settings.freeRequests||settings.priceCents===0?"Enviar mi canción":`Pagar ${money(settings.priceCents,settings.currency)} con Bizum`}</button>
 </form>
}
