import "server-only"
import { randomUUID } from "node:crypto"
import { sql } from "@/lib/db"
import { createPrivateToken,createPublicReference,hashPrivateToken,isValidPrivateToken,roundMessage } from "./domain"
import { encryptToken } from "./token"
import type { PublicRound,SongRequestItem,SongRequestPass,SongRequestRound,RoundStatus } from "./types"

export async function getActiveRound():Promise<SongRequestRound|null>{const rows=await sql`SELECT * FROM song_request_rounds WHERE status IN ('open','paused','full','last_round') ORDER BY created_at DESC LIMIT 1` as SongRequestRound[];return rows[0]||null}
export function publicRound(round:SongRequestRound|null):PublicRound{if(!round)return{status:"closed",capacity:0,occupied:0,available:0,percent:0,message:roundMessage("closed")};const available=Math.max(0,round.capacity-round.reserved_slots);return{status:round.status,capacity:round.capacity,occupied:round.reserved_slots,available,percent:Math.round(round.reserved_slots/round.capacity*100),message:round.message||roundMessage(round.status)}}
export async function expirePasses(){await sql`WITH targets AS (SELECT id,round_id,reserved_song_count FROM song_requests WHERE status IN ('pending_manual_payment','payment_reported') AND expires_at<=now() FOR UPDATE), expired AS (UPDATE song_requests sr SET status='expired',updated_at=now() FROM targets t WHERE sr.id=t.id RETURNING t.round_id,t.reserved_song_count), released AS (SELECT round_id,SUM(reserved_song_count)::int slots FROM expired GROUP BY round_id) UPDATE song_request_rounds r SET reserved_slots=GREATEST(0,r.reserved_slots-x.slots),status=CASE WHEN r.status='full' THEN r.reopen_status ELSE r.status END,updated_at=now() FROM released x WHERE r.id=x.round_id`}
export async function getPublicRound(){await expirePasses();return publicRound(await getActiveRound())}
export async function createPass(input:{bizumName:string;whatsapp:string;amountCents:number;songCount:number}){for(let attempt=0;attempt<12;attempt++){const id=randomUUID(),token=createPrivateToken(),reference=createPublicReference();try{const rows=await sql`WITH available_round AS (SELECT id FROM song_request_rounds WHERE status IN ('open','last_round') ORDER BY created_at DESC LIMIT 1), reserved AS (UPDATE song_request_rounds r SET reserved_slots=r.reserved_slots+${input.songCount},reopen_status=CASE WHEN r.status='last_round' THEN 'last_round' ELSE r.reopen_status END,status=CASE WHEN r.reserved_slots+${input.songCount}=r.capacity THEN 'full' ELSE r.status END,updated_at=now() FROM available_round a WHERE r.id=a.id AND r.reserved_slots+${input.songCount}<=r.capacity RETURNING r.id) INSERT INTO song_requests(id,round_id,public_reference,private_token_hash,private_token_encrypted,bizum_name,whatsapp_number,amount_cents,reserved_song_count,payment_mode,status,expires_at) SELECT ${id},reserved.id,${reference},${hashPrivateToken(token)},${encryptToken(token)},${input.bizumName},${input.whatsapp},${input.amountCents},${input.songCount},'manual_bizum','pending_manual_payment',${new Date(Date.now()+30*60_000).toISOString()} FROM reserved RETURNING *` as SongRequestPass[];if(!rows[0])throw new Error("CAPACITY_EXCEEDED");return{pass:rows[0],token}}catch(error){if(error instanceof Error&&error.message==="CAPACITY_EXCEEDED")throw error;if(attempt===11)throw error}}throw new Error("REFERENCE_UNAVAILABLE")}
export async function getPassByToken(token:string){if(!isValidPrivateToken(token))return null;await expirePasses();const hash=hashPrivateToken(token);const rows=await sql`SELECT * FROM song_requests WHERE private_token_hash=${hash}` as SongRequestPass[];return rows[0]||null}
export async function getItems(passId:string){return await sql`SELECT * FROM song_request_items WHERE song_request_id=${passId} ORDER BY position` as SongRequestItem[]}
export async function reportManualPayment(token:string){if(!isValidPrivateToken(token))return null;const hash=hashPrivateToken(token);const rows=await sql`UPDATE song_requests SET status='payment_reported',payment_reported_at=COALESCE(payment_reported_at,now()),updated_at=now() WHERE private_token_hash=${hash} AND status IN ('pending_manual_payment','payment_reported') AND expires_at>now() RETURNING *` as SongRequestPass[];return rows[0]||null}
export async function confirmManualPayment(id:string,actor:string){const rows=await sql`UPDATE song_requests SET status='song_selection_open',paid_at=COALESCE(paid_at,now()),confirmed_by=COALESCE(confirmed_by,${actor}),updated_at=now() WHERE id=${id} AND payment_mode='manual_bizum' AND status IN ('payment_reported','song_selection_open') RETURNING *` as SongRequestPass[];return rows[0]||null}
export async function releasePass(id:string,to:"payment_not_found"|"cancelled"|"expired"){const rows=await sql`WITH released AS (UPDATE song_requests SET status=${to},updated_at=now() WHERE id=${id} AND status IN ('pending_manual_payment','payment_reported','paid','song_selection_open') RETURNING round_id,reserved_song_count), adjusted AS (UPDATE song_request_rounds r SET reserved_slots=GREATEST(0,r.reserved_slots-x.reserved_song_count),status=CASE WHEN r.status='full' THEN r.reopen_status ELSE r.status END,updated_at=now() FROM released x WHERE r.id=x.round_id RETURNING r.id) SELECT id FROM adjusted` as {id:string}[];return Boolean(rows.length)}
export async function submitSongs(token:string,items:{title:string;artist:string}[]){const pass=await getPassByToken(token);if(!pass||pass.status!=="song_selection_open"||items.length!==pass.reserved_song_count)throw new Error("SELECTION_NOT_ALLOWED");const payload=JSON.stringify(items.map((item,index)=>({...item,position:index+1})));const inserted=await sql`WITH locked AS (UPDATE song_requests SET status='songs_submitted',updated_at=now() WHERE id=${pass.id} AND status='song_selection_open' RETURNING id) INSERT INTO song_request_items(id,song_request_id,position,title,artist) SELECT gen_random_uuid(),locked.id,x.position,x.title,NULLIF(x.artist,'') FROM locked CROSS JOIN jsonb_to_recordset(${payload}::jsonb) AS x(position int,title text,artist text) RETURNING *` as SongRequestItem[];if(inserted.length!==items.length)throw new Error("SELECTION_CONFLICT");return inserted}
export async function listPasses(){return await sql`SELECT * FROM song_requests ORDER BY CASE status WHEN 'payment_reported' THEN 1 WHEN 'songs_submitted' THEN 2 ELSE 3 END,payment_reported_at ASC NULLS LAST,created_at DESC` as SongRequestPass[]}
export async function listRounds(){return await sql`SELECT * FROM song_request_rounds ORDER BY created_at DESC` as SongRequestRound[]}
export async function setRoundStatus(id:string,status:RoundStatus){const rows=await sql`UPDATE song_request_rounds SET status=${status},reopen_status=CASE WHEN ${status}='last_round' THEN 'last_round' WHEN ${status}='open' THEN 'open' ELSE reopen_status END,updated_at=now() WHERE id=${id} RETURNING *` as SongRequestRound[];return rows[0]}
export async function createRound(name:string,capacity:number){const rows=await sql`WITH closed AS (UPDATE song_request_rounds SET status='closed',updated_at=now() WHERE status IN ('open','paused','full','last_round') RETURNING id) INSERT INTO song_request_rounds(id,name,status,capacity) VALUES(${randomUUID()},${name},'open',${capacity}) RETURNING *` as SongRequestRound[];return rows[0]}
export async function markItemPlayed(id:string){const rows=await sql`UPDATE song_request_items SET status='played',played_at=COALESCE(played_at,now()),updated_at=now() WHERE id=${id} AND status='queued' RETURNING *` as SongRequestItem[];return rows[0]}
export async function listAllItems(){return await sql`SELECT * FROM song_request_items ORDER BY song_request_id,position` as SongRequestItem[]}
export async function updateRoundCapacity(id:string,capacity:number){const rows=await sql`UPDATE song_request_rounds SET capacity=${capacity},status=CASE WHEN reserved_slots>=${capacity} THEN 'full' WHEN status='full' THEN reopen_status ELSE status END,updated_at=now() WHERE id=${id} AND ${capacity}>=reserved_slots RETURNING *` as SongRequestRound[];return rows[0]}
export async function updateSongItem(id:string,title:string,artist:string){const rows=await sql`UPDATE song_request_items SET title=${title},artist=${artist||null},updated_at=now() WHERE id=${id} AND status='queued' RETURNING *` as SongRequestItem[];return rows[0]}
export async function archivePass(id:string){const rows=await sql`UPDATE song_requests SET status='archived',updated_at=now() WHERE id=${id} AND status IN ('songs_submitted','queued','played','payment_not_found','cancelled','expired') RETURNING id` as {id:string}[];return Boolean(rows.length)}
