"use client"
import { useState,useTransition } from "react"
import { saveSongRequestSettingsAction,transitionSongRequestAction } from "@/app/actions/song-requests"
import type { SongRequest,SongRequestSettings,RequestStatus } from "@/lib/song-requests/types"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { toast } from "sonner"
const paymentLabels:Record<string,string>={not_required:"Gratis",pending:"Pendiente",processing:"Procesando",paid:"Pagado",failed:"Fallido",cancelled:"Cancelado",refunded:"Reembolsado",partially_refunded:"Reembolso parcial",expired:"Caducado"}
const requestLabels:Record<string,string>={pending_payment:"Esperando pago",paid:"Nueva",accepted:"Aceptada",played:"Reproducida",rejected:"Rechazada",refunded:"Reembolsada",expired:"Caducada",archived:"Archivada"}
export function SongRequestsManager({initialSettings,requests,qrUrl}:{initialSettings:SongRequestSettings;requests:SongRequest[];qrUrl:string}){const [s,setS]=useState(initialSettings);const [pending,start]=useTransition();function save(){start(async()=>{try{await saveSongRequestSettingsAction(s);toast.success("Configuración guardada")}catch{toast.error("No se pudo guardar")}})}function move(id:string,to:RequestStatus){start(async()=>{try{await transitionSongRequestAction({id,to});toast.success("Estado actualizado")}catch(e){toast.error(e instanceof Error?e.message:"No se pudo actualizar")}})}const qr="/api/admin/song-request-qr?format=svg";const png="/api/admin/song-request-qr?format=png"
return <div className="space-y-8"><header><h1 className="text-3xl font-black">Solicitudes de canciones</h1><p className="text-muted-foreground">Control rápido de la noche y cola privada.</p></header><section className="rounded-2xl border bg-card p-4"><h2 className="mb-4 text-xl font-bold">Estado de la noche</h2><div className="grid gap-3 sm:grid-cols-3">{(["open","paused","closed"] as const).map(v=><Button key={v} type="button" variant={s.serviceStatus===v?"default":"outline"} className="min-h-12" onClick={()=>setS({...s,serviceStatus:v})}>{v==="open"?"Abierto":v==="paused"?"Pausado":"Cerrado"}</Button>)}</div><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="font-medium">Precio (céntimos)<Input type="number" min={0} max={100000} value={s.priceCents} onChange={e=>setS({...s,priceCents:Number(e.target.value)})}/></label><label className="flex min-h-12 items-center gap-3"><input type="checkbox" className="h-6 w-6" checked={s.freeRequests} onChange={e=>setS({...s,freeRequests:e.target.checked})}/> Solicitudes gratis</label><label className="font-medium">Evento activo<Input value={s.eventName} maxLength={120} onChange={e=>setS({...s,eventName:e.target.value})}/></label><label className="font-medium">ID del evento<Input value={s.eventId} maxLength={80} onChange={e=>setS({...s,eventId:e.target.value})}/></label><label className="font-medium sm:col-span-2">Mensaje público<Input value={s.publicMessage} maxLength={500} onChange={e=>setS({...s,publicMessage:e.target.value})}/></label><label className="flex items-center gap-3"><input type="checkbox" className="h-6 w-6" checked={s.peakMode} onChange={e=>setS({...s,peakMode:e.target.checked})}/> Hora punta</label><label className="flex items-center gap-3"><input type="checkbox" className="h-6 w-6" checked={s.lastRound} onChange={e=>setS({...s,lastRound:e.target.checked})}/> Última ronda</label></div><Button disabled={pending} onClick={save} className="mt-4 min-h-12 w-full sm:w-auto">{pending?"Guardando…":"Guardar cambios"}</Button></section>
<section className="rounded-2xl border bg-card p-4"><h2 className="text-xl font-bold">QR permanente</h2><div className="mt-4 flex flex-col gap-5 sm:flex-row"><div className="print-poster rounded-xl bg-white p-4 text-center text-black"><strong className="block text-2xl">PIDE TU CANCIÓN</strong><img src={qr} alt={`Código QR para ${qrUrl}`} width="240" height="240" className="mx-auto my-2"/><p>Escanea · paga · envía tu petición</p><strong>DJ JOHNX</strong></div><div className="flex flex-col gap-3"><a className="rounded-lg border px-4 py-3 text-center font-bold" href={qr} download="djjohnx-mi-cancion.svg">Descargar SVG</a><a className="rounded-lg border px-4 py-3 text-center font-bold" href={png} download="djjohnx-mi-cancion.png">Descargar PNG</a><Button variant="outline" onClick={()=>window.print()}>Imprimir cartel</Button><code className="break-all text-xs">{qrUrl}</code></div></div></section>
<section><h2 className="mb-3 text-xl font-bold">Cola ({requests.length})</h2><div className="space-y-3">{requests.map(r=><article key={r.id} className="rounded-2xl border bg-card p-4"><div className="flex justify-between gap-3"><div><h3 className="text-lg font-black">{r.song_title}</h3><p className="text-muted-foreground">{r.artist_name||"Artista no indicado"}</p></div><div className="text-right text-sm"><strong>{requestLabels[r.request_status]}</strong><br/><span>{paymentLabels[r.payment_status]}</span></div></div><div className="mt-3 grid gap-1 text-sm sm:grid-cols-2"><p>Nombre: {r.requester_name||"—"}</p><p>Mesa/zona: {r.location_label||"—"}</p><p>Dedicatoria: {r.dedication||"—"}</p><p>Creada: {new Date(r.created_at).toLocaleString("es-ES")}</p><p>Pagada: {r.paid_at?new Date(r.paid_at).toLocaleString("es-ES"):"—"}</p><p>Importe: {(r.amount_cents/100).toLocaleString("es-ES",{style:"currency",currency:r.currency})}</p><p>Referencia: {r.payment_reference}</p><p>Evento: {r.event_id} · {r.payment_provider}</p></div><div className="mt-4 flex flex-wrap gap-2">{r.request_status==="paid"&&<Button disabled={pending} onClick={()=>move(r.id,"accepted")}>Aceptar</Button>}{r.request_status==="accepted"&&<Button disabled={pending} onClick={()=>move(r.id,"played")}>Reproducida</Button>}{["paid","accepted"].includes(r.request_status)&&<Button variant="destructive" disabled={pending} onClick={()=>move(r.id,"rejected")}>Rechazar</Button>}{r.request_status!=="archived"&&<Button variant="outline" disabled={pending} onClick={()=>move(r.id,"archived")}>Archivar</Button>}</div></article>)}{!requests.length&&<p className="rounded-xl border border-dashed p-8 text-center text-muted-foreground">Todavía no hay solicitudes.</p>}</div></section></div>}
